import {
  ClerkProvider,
  ClerkLoaded
} from '@clerk/nextjs'
import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/Navbar';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Navbar />
          <ClerkLoaded>{children}</ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  )
}
